#pragma once
namespace MDServerNetLib
{
	// 에러 코드는 1 ~ 200까지 사용한다. 에러 코드 의미에 따라서 코드의 범위를 나누는것이 좋다.
	enum class NET_ERROR_CODE : short
	{
		NONE = 0,

		SERVER_SOCKET_STARTUP_FAIL = 11,
		SERVER_SOCKET_CREATE_FAIL = 12,
		SERVER_SOCKET_SO_REUSEADDR_FAIL = 13,
		SERVER_SOCKET_BIND_AND_LISTEN_FAIL = 14,
		SERVER_SOCKET_FIONBIO_FAIL = 16,
		SERVER_CP_CREATE_FAIL = 17,
		SERVER_CONFIG_MISSING = 18,
		SERVER_LOGGER_MISSING = 19,

		SEND_CLOSE_SOCKET = 21,
		SEND_SIZE_ZERO = 22,
		CLIENT_SEND_BUFFER_FULL = 23,
		CLIENT_FLUSH_SEND_BUFF_REMOTE_CLOSE = 24,


		ACCEPT_API_ERROR = 26,
		ACCEPT_MAX_SESSION_COUNT = 27,
		ACCEPT_API_WSAEWOULDBLOCK = 28,

		RECV_API_ERROR = 32,
		RECV_BUFFER_OVERFLOW = 32,
		RECV_REMOTE_CLOSE = 33,
		RECV_PROCESS_NOT_CONNECTED = 34,
		RECV_CLIENT_MAX_PACKET = 35,

		WORK_THREAD_CREATE_FAIL = 41,
		SESSION_POOL_CREATE_FAIL = 42,
	};
}